# Generated by Django 5.2.12 on 2026-03-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='auction',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days'),
        ),
        migrations.AddField(
            model_name='auction',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='Duration in hours'),
        ),
        migrations.AddField(
            model_name='auction',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When auction ends (computed from start_time + duration)', null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When auction goes live (can be future)', null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
