# Generated by Django 5.2.12 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_add_duration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="activate_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="end_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
