# Generated by Django 5.2.12 on 2026-03-18 14:39

import auctions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def forwards_copy_auction_to_item(apps, schema_editor):
    Auction = apps.get_model("auctions", "Auction")
    Item = apps.get_model("auctions", "Item")

    # Create an Item per existing Auction row, then link auction.item.
    for auction in Auction.objects.all().iterator():
        legacy_images = []
        try:
            legacy_images = list(getattr(auction, "image_urls", []) or [])
        except Exception:
            legacy_images = []

        item = Item.objects.create(
            owner_id=auction.seller_id,
            title=getattr(auction, "title", "") or "Untitled item",
            description=getattr(auction, "description", "") or "",
            category_id=getattr(auction, "category_id", None),
            attributes={"legacy_image_urls": legacy_images} if legacy_images else {},
        )
        auction.item_id = item.id
        auction.save(update_fields=["item"])


def backwards_copy_item_to_auction(apps, schema_editor):
    # Best-effort reverse: does not restore image_urls.
    Auction = apps.get_model("auctions", "Auction")
    for auction in Auction.objects.select_related("item").all().iterator():
        item = getattr(auction, "item", None)
        if not item:
            continue
        if hasattr(auction, "title"):
            auction.title = item.title
        if hasattr(auction, "description"):
            auction.description = item.description
        if hasattr(auction, "category_id"):
            auction.category_id = item.category_id
        auction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_add_task_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='digital', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('platform', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(blank=True, max_length=80)),
                ('license_type', models.CharField(blank=True, max_length=80)),
                ('delivery_method', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='auctions.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='auctions.item'),
        ),
        migrations.RunPython(forwards_copy_auction_to_item, backwards_copy_item_to_auction),
        migrations.AlterField(
            model_name="auction",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="auctions", to="auctions.item"),
        ),
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='title',
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=auctions.models.item_image_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.item')),
            ],
            options={
                'db_table': 'item_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
