# Generated by Django 5.2.12 on 2026-03-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_category_remove_auction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='auctions.item'),
        ),
    ]
